name = "KD"
description = "KD is helping you build modern documentation."
license = "MIT"
homepage = "https://github.com/"

[extra]

[author]
name = "Jas"
homepage = "https://github.com/"

[original]
author =  "Jas"
homepage = "https://kd.ms/"

